CREATE DATABASE SMARTHOME;
USE SMARTHOME;

CREATE TABLE USR(
    ID_USR INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAMEUSE VARCHAR(20),
    TYPEUSE VARCHAR(15)
);

CREATE TABLE EMPLACMENT(
    ID_EMP INT(10) AUTO_INCREMENT PRIMARY KEY ,
    DESCRIPT VARCHAR(50)
);

CREATE TABLE MOTE(
ID_MOTE INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
IP_ADD VARCHAR(15),
ID_EMP INT(10),
FOREIGN KEY (ID_EMP) REFERENCES EMPLACMENT(ID_EMP)
);

CREATE TABLE CAPTEUR(
    ID_CAPT INT(10) AUTO_INCREMENT PRIMARY KEY  ,
    NOM VARCHAR(15),
    TYPEC VARCHAR(7),
    ID_MOTE INT(10),
    FOREIGN KEY (ID_MOTE) REFERENCES MOTE(ID_MOTE)
)

CREATE TABLE DATACAP(
    ID_DCAP INT(20) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    VALCAP VARCHAR(7),
    DESCR VARCHAR(20),
    DCAP DATE ,
    ID_CAPT INT(10),
    FOREIGN KEY (ID_CAPT) REFERENCES CAPTEUR(ID_CAPT)
);

CREATE TABLE CAPT_USR(
ID_USR INT(10) , 
ID_CAPT INT(10),
MESSAGE VARCHAR(30),
FOREIGN KEY (ID_CAPT) REFERENCES CAPTEUR(ID_CAPT),
FOREIGN KEY (ID_USR) REFERENCES USR(ID_USR),
PRIMARY KEY (ID_USR,ID_CAPT)
);

CREATE TABLE ALARM(
    ID_ALARM INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NIV VARCHAR(15),
    ACT VARCHAR(15),
    STAT VARCHAR(6),
    DATEE DATE,
    NOM VARCHAR(15),
    ID_CAPT INT(10),
    ID_MOTE INT(10),
    DESCRIPT VARCHAR(15),
FOREIGN KEY (ID_CAPT) REFERENCES CAPTEUR(ID_CAPT),    
FOREIGN KEY (ID_MOTE) REFERENCES MOTE(ID_MOTE)
);

CREATE TABLE ACTIONNEUR(
    ID_ACT INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMACT VARCHAR(20),
    TYPEAC VARCHAR(7),
    ID_MOTE INT(10) ,
    FOREIGN KEY (ID_MOTE) REFERENCES MOTE(ID_MOTE)
);

CREATE TABLE ACT_USR(
ID_USR INT(10) , 
ID_ACT INT(10),
FOREIGN KEY (ID_ACT) REFERENCES ACTIONNEUR(ID_ACT),
FOREIGN KEY (ID_USR) REFERENCES USR(ID_USR),
PRIMARY KEY (ID_USR,ID_CAPT)
);

CREATE TABLE DATACTIONNEUR(
    ID_DACT INT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCR VARCHAR(20),
    VALDAC VARCHAR(7),
    DAC DATE ,
    ID_ACT INT(10),
    FOREIGN KEY (ID_ACT) REFERENCES ACTIONNEUR(ID_ACT)
);
